version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "web"
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - project
  database:
    container_name: "database"
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_PASSWORD: student
      MYSQL_ROOT_PASSWORD: student
      MYSQL_DATABASE: moje_ligi
      MYSQL_USER: student
    ports:
      - "3306:3306"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - project

networks:
  project:
    driver: bridge